/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:c59074c73fa4cfe9a4bf5251d7889a74:b37a93bfdbcb9cbb1eae31fd95611961:abd75b053584001b4f6fc8464b42708a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
    public class texture
    {
        public const string Background = "background";
        public const string Buttondown = "buttondown";
        public const string Buttonup = "buttonup";
        public const string Checkbox = "checkbox";
        public const string Checkboxclicked = "checkboxclicked";
        public const string Corgi = "Corgi";
        public const string Floatingbackground = "floatingbackground";
        public const string Recessed = "recessed";
        public const string Whitetexture = "whitetexture";
    }
}