/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:3d424ab8f781ac7f078085c27e7770ac:4516c436c946eafbc9564d31a4bbd847:abd75b053584001b4f6fc8464b42708a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class texture
	{
		public const string Background = "background";
		public const string Floatingbackground = "floatingbackground";
		public const string Whitetexture = "whitetexture";
	}
}