/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:07a633134074c224782db6ecf03f3562:4cffb1487945519c1fe08329dc3af2f8:ba59717a9d6b8a11554cadb3da0d4bea$
 *
 */
namespace TexturePackerLoader
{
	public static class Sprites
	{
		public const string Items_computer = "Items/computer";
		public const string Items_hat = "Items/hat";
		public const string UI_background = "UI/background";
		public const string UI_briefcase = "UI/briefcase";
		public const string UI_briefcasesmall = "UI/briefcasesmall";
		public const string UI_floatingbackground = "UI/floatingbackground";
		public const string UI_textbottom = "UI/textbottom";
	}
}